id: P000623
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:52:31.902409
source_metadata:
  id: bdr:W2CZ7860
  title: དགེ་འདུན་གྲུབ་པ་དཔལ་བཟང་པོའི་རྣམ་ཐར་
  author: ''
  volumes:
    8cdf6ae26f0b490aa678432616469781:
      image_group_id: I1KG2842
      title: ''
      volume_number: 1
      total_pages: 128
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
