id: P000623
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7860
  title: དགེ་འདུན་གྲུབ་པ་དཔལ་བཟང་པོའི་རྣམ་ཐར་
  author: ''
  volumes:
    8cdf6ae26f0b490aa678432616469781:
      image_group_id: I1KG2842
      title: ''
      volume_number: 1
      total_pages: 128
