id: I4AC6C683
legacy_id: P000623
ocr_import_info:
  bdrc_scan_id: W2CZ7860
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T09:23:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:23:27.734337+00:00'
last_modified: 2022-09-02 23:23:50.315695
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7860
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7860
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་འདུན་གྲུབ་པ་དཔལ་བཟང་པོའི་རྣམ་ཐར།
  author: པཎ་ཆེན་ཡེ་ཤེས་རྩེ་མོ།
statistics:
  ocr_word_mean_confidence_index: 0.5956943487346706
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I1KG2842:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2842
      total_pages: 128
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2842.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5956943487346706
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
